// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yvitrtenkltnzzhlozma.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl2aXRydGVua2x0bnp6aGxvem1hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA0MjU3MDcsImV4cCI6MjA1NjAwMTcwN30.nG0yH3Stx3EX6iLum1j_yWERJ24IqEhv1-189GzDXPA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);